spring.application.name=learning-platform

# Kết nối tới Database learning-db trong Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/learning_web_platform
spring.datasource.username=postgres
spring.datasource.password=123456

# Cấu hình Hibernate tự động tạo bảng từ code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Tạm thời tắt Security mặc định để test
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quizwhite212@gmail.com
spring.mail.password=riqsfmozeazssfbt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cấu hình Cloudinary
cloudinary.cloud-name=dt5wzidai
cloudinary.api-key=945982914779299
cloudinary.api-secret=lqsNpivJ-HQsOXhDIiHO_KXMCAs


# ================= CẤU HÌNH ZALOPAY SANDBOX =================
zalopay.endpoint.create=https://sb-openapi.zalopay.vn/v2/create
zalopay.app-id=2553
zalopay.key1=PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL
zalopay.key2=kLtgPl8YESVjmLSREuMDJAMGWlfxnRVk